name: project_one
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  widget:
    path: module/share/widget

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true