name: project_one
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  source:
    path: module/source
  common:
    path: module/common
  theme:
    path: module/theme
  widget:
    path: module/widget

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true