name: project_one
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Local
  core:
    path: module/layer/core
  domain:
    path: module/layer/domain
  common:
    path: module/share/common
  content:
    path: module/share/content
  theme:
    path: module/share/theme
  widget:
    path: module/share/widget
  # Pub
  flutter_bloc: any

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true