name: common
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Local
  core:
    path: ../../layer/core
  domain:
    path: ../../layer/domain
  # Pub
  flutter_bloc: any

dev_dependencies:
  flutter_lints: ^2.0.0